FROM golang:1.11.0

ENV SRC_DIR=/go/src/app

WORKDIR "${SRC_DIR}"

RUN apt-get -y update
RUN apt-get -y upgrade
RUN mkdir -p /server

COPY . "${SRC_DIR}"

RUN make
RUN mv dist/app /server/app

EXPOSE 3000

WORKDIR /server

CMD ["./app"]
